version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install && npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:8.10
    steps:
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - checkout
      # run tests!
      - run:
          name: Run tests with coverage
          command: |
            npm install
            npm test --coverage

  deploy:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - checkout
      - run:
          name: Install python
          command: sudo python get-pip.py

      - run:
          name: Install AWS cli
          command: sudo pip install awscli

      - run:
          name: Deploy
          # command: sls deploy --stage pre
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ];
            then
              npm run deploy-staging
              
            elif [ "${CIRCLE_BRANCH}" == "master" ];
            then
              npm run deploy-prod
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - dev
                - production
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - dev
                - production
